;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "update-leiningen-dependencies-skill")
(def path ".")
(def version "0.1.13")
(def tag "v0.1.13")
(def generated-at "2020-05-07T17:05:42Z")
