;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "update-leiningen-dependencies-skill")
(def path ".")
(def version "0.1.20")
(def tag "0.1.20")
(def generated-at "2020-06-05T19:29:37Z")
